<a href="https://colab.research.google.com/github/Annepikson/HypatiaAcademy/blob/master/2024_7_12_OR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np


inputs = np.array([[1,1],
                   [0,0],
                  [1,0],
                   [0,1]])


labels = np.array([[0],
                   [1],
                   [1],
                   [1]])

array([[0],
       [1],
       [1],
       [1]])

In [7]:
model = keras.Sequential([
    Dense(4, activation="relu", input_shape=(2,)),  # Correct input shape
    Dense(1, activation="sigmoid")  # One output neuron with sigmoid activation
])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(inputs, labels, epochs=10000, verbose=0)

loss, accuracy = model.evaluate(inputs, labels, verbose=0)
print(f"Accuracy: {accuracy*100:.2f}%")


In [8]:
#model.predict([1,1])

predictions=model.predict(inputs)

np.set_printoptions(suppress=True)

np.column_stack([labels,predictions])

1/1 [==============================] - 0s 197ms/step


array([[0.        , 0.52423853],
       [1.        , 0.5       ],
       [1.        , 0.49864614],
       [1.        , 0.47276151]])

In [12]:
# Apply threshold to convert probabilities to class labels
predicted_classes = (predictions <= 0.5).astype(int)
print("\n Predictions:")
print(predicted_classes)


print("\n inputs, labels, predicted %, predicted 1 or 0")
np.column_stack([inputs[:4], labels[:4],predictions,predicted_classes])


 Predictions:
[[0]
 [1]
 [1]
 [1]]

 inputs, labels, predicted %, predicted 1 or 0


array([[1.        , 1.        , 0.        , 0.52423853, 0.        ],
       [0.        , 0.        , 1.        , 0.5       , 1.        ],
       [1.        , 0.        , 1.        , 0.49864614, 1.        ],
       [0.        , 1.        , 1.        , 0.47276151, 1.        ]])

In [14]:
(predictions <= 0.5).astype(int)

array([[0],
       [1],
       [1],
       [1]])

In [15]:
inputs[0]

array([1, 1])