<a href="https://colab.research.google.com/github/Annepikson/HypatiaAcademy/blob/master/7_6_2024_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [590]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from pylab import *
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


df = pd.read_csv("https://raw.githubusercontent.com/Annepikson/HypatiaAcademy/master/ml/Life%20Expectancy%20Data.csv")

df


Country  Year      Status  Life expectancy   Adult Mortality  \
0     Afghanistan  2015  Developing              65.0            263.0   
1     Afghanistan  2014  Developing              59.9            271.0   
2     Afghanistan  2013  Developing              59.9            268.0   
3     Afghanistan  2012  Developing              59.5            272.0   
4     Afghanistan  2011  Developing              59.2            275.0   
...           ...   ...         ...               ...              ...   
2933     Zimbabwe  2004  Developing              44.3            723.0   
2934     Zimbabwe  2003  Developing              44.5            715.0   
2935     Zimbabwe  2002  Developing              44.8             73.0   
2936     Zimbabwe  2001  Developing              45.3            686.0   
2937     Zimbabwe  2000  Developing              46.0            665.0   

      infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
0                62     0.01               71.279624         65.0      1154   
1                64     0.01               73.523582         62.0       492   
2                66     0.01               73.219243         64.0       430   
3                69     0.01               78.184215         67.0      2787   
4                71     0.01                7.097109         68.0      3013   
...             ...      ...                     ...          ...       ...   
2933             27     4.36                0.000000         68.0        31   
2934             26     4.06                0.000000          7.0       998   
2935             25     4.43                0.000000         73.0       304   
2936             25     1.72                0.000000         76.0       529   
2937             24     1.68                0.000000         79.0      1483   

       BMI   under-five deaths   Polio  Total expenditure  Diphtheria   \
0      19.1                  83    6.0               8.16         65.0   
1      18.6                  86   58.0               8.18         62.0   
2      18.1                  89   62.0               8.13         64.0   
3      17.6                  93   67.0               8.52         67.0   
4      17.2                  97   68.0               7.87         68.0   
...     ...                 ...    ...                ...          ...   
2933   27.1                  42   67.0               7.13         65.0   
2934   26.7                  41    7.0               6.52         68.0   
2935   26.3                  40   73.0               6.53         71.0   
2936   25.9                  39   76.0               6.16         75.0   
2937   25.5                  39   78.0               7.10         78.0   

       HIV/AIDS         GDP  Population   thinness  1-19 years  \
0           0.1  584.259210  33736494.0                   17.2   
1           0.1  612.696514    327582.0                   17.5   
2           0.1  631.744976  31731688.0                   17.7   
3           0.1  669.959000   3696958.0                   17.9   
4           0.1   63.537231   2978599.0                   18.2   
...         ...         ...         ...                    ...   
2933       33.6  454.366654  12777511.0                    9.4   
2934       36.7  453.351155  12633897.0                    9.8   
2935       39.8   57.348340    125525.0                    1.2   
2936       42.1  548.587312  12366165.0                    1.6   
2937       43.5  547.358878  12222251.0                   11.0   

       thinness 5-9 years  Income composition of resources  Schooling  
0                    17.3                            0.479       10.1  
1                    17.5                            0.476       10.0  
2                    17.7                            0.470        9.9  
3                    18.0                            0.463        9.8  
4                    18.2                            0.454        9.5  
...                   ...                              ...

In [591]:
df.columns = df.columns.str.strip()


In [592]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Country                          2938 non-null   object 
 1   Year                             2938 non-null   int64  
 2   Status                           2938 non-null   object 
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64  
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64  
 10  BMI                              2904 non-null   float64
 11  under-five deaths                2938 non-null   int64  
 12  Polio               

In [593]:
y = df.rank

In [594]:
x1 = df['Alcohol']

In [595]:
# Handle missing values by filling them with 0
df['Alcohol'] = df['Alcohol'].fillna(0)

# Convert the 'Alcohol' column to integers
df['Alcohol'] = df['Alcohol'].astype(int)

In [596]:
import re

def tonumber(n):
    s = str(n)  # Convert the value to strin
    s = re.sub(r'[^0-9.]', '', s)  # Remove all characters except digits and the decimal point
    return int(float(s))  # Convert to float first, then to int
tonumber('0.01')

0

In [597]:
x2 = df['Diphtheria']
print(x2)


0       65.0
1       62.0
2       64.0
3       67.0
4       68.0
        ... 
2933    65.0
2934    68.0
2935    71.0
2936    75.0
2937    78.0
Name: Diphtheria, Length: 2938, dtype: float64


In [598]:
df['Diphtheria'] = df['Diphtheria'].fillna(0)
df['Diphtheria'] = df['Diphtheria'].astype(int)
tonumber('65.0')

65

In [599]:
x3 = df['under-five deaths']
x3

0       83
1       86
2       89
3       93
4       97
        ..
2933    42
2934    41
2935    40
2936    39
2937    39
Name: under-five deaths, Length: 2938, dtype: int64

In [600]:
x4 = df['percentage expenditure']
x4
tonumber('71.279624')


71

In [601]:
x5 = df['Status']
x5

0       Developing
1       Developing
2       Developing
3       Developing
4       Developing
           ...    
2933    Developing
2934    Developing
2935    Developing
2936    Developing
2937    Developing
Name: Status, Length: 2938, dtype: object

In [602]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

x5=le.fit_transform(df['Status'])

x5

array([1, 1, 1, ..., 1, 1, 1])

In [603]:
y=df['Life expectancy'].values
y


array([65. , 59.9, 59.9, ..., 44.8, 45.3, 46. ])

In [604]:
x1=df['Alcohol'].apply(tonumber)
x1

0       0
1       0
2       0
3       0
4       0
       ..
2933    4
2934    4
2935    4
2936    1
2937    1
Name: Alcohol, Length: 2938, dtype: int64

In [605]:
x2=df['Diphtheria'].apply(tonumber)
x2

0       65
1       62
2       64
3       67
4       68
        ..
2933    65
2934    68
2935    71
2936    75
2937    78
Name: Diphtheria, Length: 2938, dtype: int64

In [606]:
x3=df['under-five deaths'].apply(tonumber)
x3

0       83
1       86
2       89
3       93
4       97
        ..
2933    42
2934    41
2935    40
2936    39
2937    39
Name: under-five deaths, Length: 2938, dtype: int64

In [607]:
x4=df['percentage expenditure'].apply(tonumber)
x4

0       71
1       73
2       73
3       78
4        7
        ..
2933     0
2934     0
2935     0
2936     0
2937     0
Name: percentage expenditure, Length: 2938, dtype: int64

In [608]:

import numpy as np

X=np.column_stack((x1,x2,x3,x4,x5))
X

array([[ 0, 65, 83, 71,  1],
       [ 0, 62, 86, 73,  1],
       [ 0, 64, 89, 73,  1],
       ...,
       [ 4, 71, 40,  0,  1],
       [ 1, 75, 39,  0,  1],
       [ 1, 78, 39,  0,  1]])

In [609]:
X.shape

(2938, 5)

In [610]:
y.shape

(2938,)

In [611]:
X

array([[ 0, 65, 83, 71,  1],
       [ 0, 62, 86, 73,  1],
       [ 0, 64, 89, 73,  1],
       ...,
       [ 4, 71, 40,  0,  1],
       [ 1, 75, 39,  0,  1],
       [ 1, 78, 39,  0,  1]])

In [612]:
y

array([65. , 59.9, 59.9, ..., 44.8, 45.3, 46. ])

In [613]:


# Replace NaN with zero
X[np.isnan(X)] = 0
y[np.isnan(y)] = 0


In [614]:
reg = LinearRegression()
reg.fit(X, y)

LinearRegression()

In [615]:
np.set_printoptions(suppress=True, precision=10)

print('Coefficients: \n', reg.coef_)
print('\n Intercept: \n', reg.intercept_)



Coefficients: 
 [ 0.2077523946  0.1377980969 -0.0055576274  0.0008263898 -6.9347290049]

 Intercept: 
 62.256602301956136


In [616]:

x1, x2,x3,x4,x5 = [ 0        , 65        , 83        , 71.27962362,  1]

In [618]:
y = 0.2077523946 * x1 + 0.1377980969 * x2 -0.0055576274 * x3 +  0.0008263898 * x4 - 6.9347290049 * x5 + 62.256602301956136
y

63.876371275263544